<a href="https://colab.research.google.com/github/Srivastava27/collabPython/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Creating an array

In [ ]:
l1=[1,3,4,5]
l2=[7,8,9,2]

checking the type

In [ ]:
type(l1)

list

In [ ]:
arr1=np.array(l1)
arr1

array([1, 3, 4, 5])

In [ ]:
arr1.shape

(4,)

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr2=np.array([l1,l2])
arr2

array([[1, 3, 4, 5],
       [7, 8, 9, 2]])

In [ ]:
arr2.shape

(2, 4)

In [ ]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

This is by default float

In [ ]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

here we changed it into int

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.full(50,8)

array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8])

Reshaping Array

In [ ]:
np.arange(1,26)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
arr=np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr.shape

(12,)

In [ ]:
arr.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr.reshape(6,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.arange(100).reshape(20,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

Indexing

In [ ]:
random_arr=np.random.randint(1,100,size=(10,10))
random_arr

array([[72, 37, 54, 14, 63, 91, 95,  5, 66, 79],
       [30, 45, 93, 54, 22, 19, 96, 32, 50, 61],
       [77,  4, 72, 66, 97, 86, 88, 81, 17,  5],
       [37, 29, 71, 60, 20, 27, 49, 27, 71, 77],
       [61, 22, 66, 76, 11, 11, 82, 35, 16, 14],
       [96, 94, 42, 55, 84, 94, 18, 21, 56,  9],
       [43, 90, 83, 13, 56,  1, 62, 60, 28, 16],
       [82,  1, 85, 51, 32, 94, 90, 37, 36, 79],
       [69,  2, 70, 29, 78, 27, 89, 80, 83, 53],
       [23, 36, 89, 36, 75, 12, 54, 42, 82, 67]])

In [ ]:
arr1

array([1, 3, 4, 5])

In [ ]:
arr1[2]

4

In [ ]:
random_arr[5]

array([52, 25, 57, 85, 15, 68, 27, 81, 75, 29])

In [ ]:
random_arr[5][2]

42

In [ ]:
random_arr[3:8]

array([[37, 29, 71, 60, 20, 27, 49, 27, 71, 77],
       [61, 22, 66, 76, 11, 11, 82, 35, 16, 14],
       [96, 94, 42, 55, 84, 94, 18, 21, 56,  9],
       [43, 90, 83, 13, 56,  1, 62, 60, 28, 16],
       [82,  1, 85, 51, 32, 94, 90, 37, 36, 79]])

In [ ]:
unsorted_arr=np.array([2,5,6,23,4,67])
unsorted_arr

array([ 2,  5,  6, 23,  4, 67])

In [ ]:
sorted(unsorted_arr)

[2, 4, 5, 6, 23, 67]

In [ ]:
unsorted_arr.sort()
unsorted_arr

array([ 2,  4,  5,  6, 23, 67])

In [ ]:
unsorted_arr

array([ 2,  4,  5,  6, 23, 67])

In [ ]:
sliced_arr=unsorted_arr[2:6]
sliced_arr

array([ 5,  6, 23, 67])

In [ ]:
sliced_arr[0]

5

In [ ]:
sliced_arr

array([ 5,  6, 23, 67])

In [ ]:
unsorted_arr

array([ 2,  4,  5,  6, 23, 67])

In [ ]:
new_arr=unsorted_arr.copy()
new_arr

array([ 2,  4,  5,  6, 23, 67])

In [ ]:
new_arr[0]=-100
new_arr

array([-100,    4,    5,    6,   23,   67])

In [ ]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[4:8]=100
arr

array([  0,   1,   2,   3, 100, 100, 100, 100,   8,   9])

In [ ]:
arr*10

array([   0,   10,   20,   30, 1000, 1000, 1000, 1000,   80,   90])

In [ ]:
arr

array([  0,   1,   2,   3, 100, 100, 100, 100,   8,   9])

In [ ]:
arr%2==0

array([ True, False,  True, False,  True,  True,  True,  True,  True,
       False])

In [ ]:
arr[arr % 2 == 0]

array([  0,   2, 100, 100, 100, 100,   8])

In [ ]:
(arr%2==0) & (arr>10)

array([False, False, False, False,  True,  True,  True,  True, False,
       False])

In [ ]:
arr[(arr%2==0) & (arr>10)]

array([100, 100, 100, 100])

In [ ]:
arr=np.random.randint(1,100,size=10)
arr

array([25, 45, 53, 58, 45, 36, 33, 22, 56, 79])

In [ ]:
arr.min()

22

In [ ]:
arr.max()

79

In [ ]:
arr.argmin()

7

In [ ]:
arr.argmax()

9

In [ ]:
arr.sum()

452

In [ ]:
np.sqrt(arr)

array([5.        , 6.70820393, 7.28010989, 7.61577311, 6.70820393,
       6.        , 5.74456265, 4.69041576, 7.48331477, 8.88819442])

In [ ]:
np.sin(arr)

array([-0.13235175,  0.85090352,  0.39592515,  0.99287265,  0.85090352,
       -0.99177885,  0.99991186, -0.00885131, -0.521551  , -0.44411267])