<a href="https://colab.research.google.com/github/Srivastava27/collabPython/blob/master/PracticeNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3])

In [3]:
arr.shape

(3,)

In [4]:
arr.size

3

In [5]:
arr.ndim

1

In [6]:
arr.dtype

dtype('int64')

In [9]:
arr[1:3]

array([2, 3])

In [10]:
arr[0]

1

In [11]:
np.mean(arr)

2.0

In [12]:
np.sum(arr)

6

In [13]:
arr+5

array([6, 7, 8])

In [14]:
arr2=[6,7,8]

In [15]:
np.concatenate((arr,arr2),axis=0)

array([1, 2, 3, 6, 7, 8])

In [16]:
arr.T

array([1, 2, 3])

In [17]:
np.random.rand(3,3)

array([[0.95572734, 0.7654318 , 0.88910464],
       [0.38069911, 0.88427797, 0.90416423],
       [0.11096562, 0.75031123, 0.48243358]])